// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
)

const createCard = `-- name: CreateCard :one
INSERT INTO lore_cards (name, type, summary, body, image_url, tags)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, type, summary, body, image_url, tags, created_at, updated_at
`

type CreateCardParams struct {
	Name     string  `json:"name"`
	Type     string  `json:"type"`
	Summary  string  `json:"summary"`
	Body     *string `json:"body"`
	ImageUrl *string `json:"image_url"`
	Tags     *string `json:"tags"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (LoreCard, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.Name,
		arg.Type,
		arg.Summary,
		arg.Body,
		arg.ImageUrl,
		arg.Tags,
	)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM lore_cards
WHERE id = ?
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteCardByName = `-- name: DeleteCardByName :exec
DELETE FROM lore_cards
WHERE name = ? collate nocase
`

func (q *Queries) DeleteCardByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCardByName, name)
	return err
}

const getCardByName = `-- name: GetCardByName :one
SELECT id, name, type, summary, body, image_url, tags, created_at, updated_at 
FROM lore_cards 
WHERE name = ? collate nocase
`

func (q *Queries) GetCardByName(ctx context.Context, name string) (LoreCard, error) {
	row := q.db.QueryRowContext(ctx, getCardByName, name)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, name, type, summary, body, image_url, tags, created_at, updated_at
FROM lore_cards
ORDER BY name
`

func (q *Queries) ListCards(ctx context.Context) ([]LoreCard, error) {
	rows, err := q.db.QueryContext(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoreCard{}
	for rows.Next() {
		var i LoreCard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Summary,
			&i.Body,
			&i.ImageUrl,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByType = `-- name: ListCardsByType :many
SELECT id, name, type, summary, body, image_url, tags, created_at, updated_at
FROM lore_cards
WHERE type = ?
ORDER BY name
`

func (q *Queries) ListCardsByType(ctx context.Context, type_ string) ([]LoreCard, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoreCard{}
	for rows.Next() {
		var i LoreCard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Summary,
			&i.Body,
			&i.ImageUrl,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardsByName = `-- name: SearchCardsByName :many
SELECT id, name, type
FROM lore_cards
WHERE name LIKE ? || '%'
ORDER BY name
LIMIT 25
`

type SearchCardsByNameRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

func (q *Queries) SearchCardsByName(ctx context.Context, dollar_1 *string) ([]SearchCardsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCardsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCardsByNameRow{}
	for rows.Next() {
		var i SearchCardsByNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE lore_cards
SET 
    name = ?,
    summary = ?,
    body = ?,
    tags = ?,
    image_url = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, type, summary, body, image_url, tags, created_at, updated_at
`

type UpdateCardParams struct {
	Name     string  `json:"name"`
	Summary  string  `json:"summary"`
	Body     *string `json:"body"`
	Tags     *string `json:"tags"`
	ImageUrl *string `json:"image_url"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (LoreCard, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.Name,
		arg.Summary,
		arg.Body,
		arg.Tags,
		arg.ImageUrl,
		arg.ID,
	)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardImage = `-- name: UpdateCardImage :one
UPDATE lore_cards
SET 
    image_url = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, type, summary, body, image_url, tags, created_at, updated_at
`

type UpdateCardImageParams struct {
	ImageUrl *string `json:"image_url"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateCardImage(ctx context.Context, arg UpdateCardImageParams) (LoreCard, error) {
	row := q.db.QueryRowContext(ctx, updateCardImage, arg.ImageUrl, arg.ID)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
