// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type LoreCard struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Summary   string  `json:"summary"`
	Body      *string `json:"body"`
	ImageUrl  *string `json:"image_url"`
	Tags      *string `json:"tags"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}
