// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"
)

const createCard = `-- name: CreateCard :one
INSERT INTO lore_cards (name, type, summary, body, image_url, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, summary, body, image_url, tags, created_at, updated_at
`

type CreateCardParams struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Summary  string   `json:"summary"`
	Body     *string  `json:"body"`
	ImageUrl *string  `json:"image_url"`
	Tags     []string `json:"tags"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (LoreCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Name,
		arg.Type,
		arg.Summary,
		arg.Body,
		arg.ImageUrl,
		arg.Tags,
	)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM lore_cards
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const deleteCardByName = `-- name: DeleteCardByName :exec
DELETE FROM lore_cards
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) DeleteCardByName(ctx context.Context, lower string) error {
	_, err := q.db.Exec(ctx, deleteCardByName, lower)
	return err
}

const getCardByName = `-- name: GetCardByName :one
SELECT id, name, type, summary, body, image_url, tags, created_at, updated_at 
FROM lore_cards 
WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) GetCardByName(ctx context.Context, lower string) (LoreCard, error) {
	row := q.db.QueryRow(ctx, getCardByName, lower)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByType = `-- name: ListCardsByType :many
SELECT id, name, type, summary, body, image_url, tags, created_at, updated_at
FROM lore_cards
WHERE type = $1
ORDER BY name
`

func (q *Queries) ListCardsByType(ctx context.Context, type_ string) ([]LoreCard, error) {
	rows, err := q.db.Query(ctx, listCardsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoreCard{}
	for rows.Next() {
		var i LoreCard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Summary,
			&i.Body,
			&i.ImageUrl,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCardsByName = `-- name: SearchCardsByName :many
SELECT id, name, type
FROM lore_cards
WHERE name ILIKE $1 || '%'
ORDER BY name
LIMIT 25
`

type SearchCardsByNameRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

func (q *Queries) SearchCardsByName(ctx context.Context, dollar_1 *string) ([]SearchCardsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchCardsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCardsByNameRow{}
	for rows.Next() {
		var i SearchCardsByNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE lore_cards
SET 
    summary = $2,
    body = $3,
    image_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, type, summary, body, image_url, tags, created_at, updated_at
`

type UpdateCardParams struct {
	ID       int32   `json:"id"`
	Summary  string  `json:"summary"`
	Body     *string `json:"body"`
	ImageUrl *string `json:"image_url"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (LoreCard, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.Summary,
		arg.Body,
		arg.ImageUrl,
	)
	var i LoreCard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Summary,
		&i.Body,
		&i.ImageUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
