// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoreCard struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Summary   string             `json:"summary"`
	Body      *string            `json:"body"`
	ImageUrl  *string            `json:"image_url"`
	Tags      []string           `json:"tags"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
