// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCard(ctx context.Context, arg CreateCardParams) (LoreCard, error)
	DeleteCard(ctx context.Context, id int32) error
	DeleteCardByName(ctx context.Context, lower string) error
	GetCardByName(ctx context.Context, lower string) (LoreCard, error)
	ListCards(ctx context.Context) ([]LoreCard, error)
	ListCardsByType(ctx context.Context, type_ string) ([]LoreCard, error)
	SearchCardsByName(ctx context.Context, dollar_1 *string) ([]SearchCardsByNameRow, error)
	UpdateCard(ctx context.Context, arg UpdateCardParams) (LoreCard, error)
}

var _ Querier = (*Queries)(nil)
